#!/usr/bin/env python3
"""Turn oracle dumps into committed golden files that dream_emit_tests replays on every host.

  write_golden.py --dumps DIR --out tests/sh4/golden --cases tools/oracle/cases.json [--cases ...]

DIR is the --keep directory of a differential.py run; only cases whose oracle dump exists are
written. Each golden records the case's inputs (image as a repo-relative path, program, registers,
fill, hash range) and the oracle's final state, one field per line. The replay test skips goldens
whose image is absent (game slices on CI)."""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import oracle  # noqa: E402

REPO = HERE.parent.parent
CT_IMAGE = "games/crazytaxi/extracted/fs/1ST_READ.BIN"


def repo_image(image: str) -> str:
    image = image.replace("${CT_IMAGE}", CT_IMAGE)
    if os.path.isabs(image):
        return os.path.relpath(image, REPO)
    if image.startswith("games/"):
        return image
    return os.path.normpath(os.path.join("tests/sh4/programs", image))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--dumps", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--cases", action="append", required=True)
    a = ap.parse_args()
    cases = []
    for path in a.cases:
        cases += json.load(open(path))
    Path(a.out).mkdir(parents=True, exist_ok=True)
    written = 0
    for case in cases:
        dump = Path(a.dumps) / f"{case['name']}.oracle.json"
        if not dump.exists():
            continue
        d = json.load(open(dump))
        if not d.get("stopped"):
            continue
        lines = ["# Generated by tools/oracle/write_golden.py from the Flycast oracle. Do not edit.",
                 f"name {case['name']}",
                 f"program {case.get('program', case['image'].rsplit('/', 1)[-1].rsplit('.', 1)[0])}",
                 f"image {repo_image(case['image'])}",
                 f"base {case['base']}", f"entry {case['entry']}",
                 f"fpscr {case.get('fpscr', '0x00040001')}"]
        for k, v in case.get("regs", {}).items():
            lines.append(f"reg {int(k[1:])} {int(v, 0) & 0xFFFFFFFF:#010x}")
        fregs = oracle.parse_fregs([f"{k}={v}" for k, v in case.get("fregs", {}).items()])
        for k in case.get("fregs", {}):
            n = int(k[2:])
            lines.append(f"freg {n} {fregs[n]:#010x}")
        if "fill" in case:
            fa, fl, fs = (int(x, 0) for x in case["fill"].split(":"))
            lines.append(f"fill {fa:#010x} {fl} {fs:#x}")
        if "hash" in case:
            ha, hl = (int(x, 0) for x in case["hash"].split(":"))
            lines.append(f"hash {ha:#010x} {hl}")
        lines.append("r " + " ".join(d["r"]))
        lines.append(f"t {d['t']}")
        lines.append(f"gbr {d['gbr']}")
        lines.append(f"mach {d['mach']}")
        lines.append(f"macl {d['macl']}")
        lines.append(f"fpul {d['fpul']}")
        lines.append(f"fpscr_out {d['fpscr']}")
        lines.append("fr " + " ".join(d["fr"]))
        lines.append("xf " + " ".join(d["xf"]))
        if "mem" in d:
            lines.append("mem " + " ".join(d["mem"]))
        (Path(a.out) / f"{case['name']}.golden").write_text("\n".join(lines) + "\n")
        written += 1
    print(f"wrote {written} goldens to {a.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
