#!/usr/bin/env python3
"""Generate runtime/src/aica/mixer_tables.inc: the AICA mixer's lookup tables.

Flycast computes these at start-up with pow()/lround(); libm results can differ in the last unit
across hosts, and ADR 16 wants the mixer bit-identical on every platform, so the tables are
generated once here (same formulas as Flycast's sgc_if.cpp staticinitialise) and committed.
"""
import math
import pathlib

EG_STEP_BITS = 16
AEG_ATTACK_SHIFT = 16

AEG_ATTACK_TIME = [
    -1, -1, 8100.0, 6900.0, 6000.0, 4800.0, 4000.0, 3400.0, 3000.0, 2400.0, 2000.0, 1700.0, 1500.0,
    1200.0, 1000.0, 860.0, 760.0, 600.0, 500.0, 430.0, 380.0, 300.0, 250.0, 220.0, 190.0, 150.0, 130.0, 110.0, 95.0,
    76.0, 63.0, 55.0, 47.0, 38.0, 31.0, 27.0, 24.0, 19.0, 15.0, 13.0, 12.0, 9.4, 7.9, 6.8, 6.0, 4.7, 3.8, 3.4, 3.0, 2.4,
    2.0, 1.8, 1.6, 1.3, 1.1, 0.93, 0.85, 0.65, 0.53, 0.44, 0.40, 0.35, 0.0, 0.0]
AEG_DSR_TIME = [
    -1, -1, 118200.0, 101300.0, 88600.0, 70900.0, 59100.0, 50700.0, 44300.0, 35500.0, 29600.0, 25300.0, 22200.0, 17700.0,
    14800.0, 12700.0, 11100.0, 8900.0, 7400.0, 6300.0, 5500.0, 4400.0, 3700.0, 3200.0, 2800.0, 2200.0, 1800.0, 1600.0, 1400.0, 1100.0,
    920.0, 790.0, 690.0, 550.0, 460.0, 390.0, 340.0, 270.0, 230.0, 200.0, 170.0, 140.0, 110.0, 98.0, 85.0, 68.0, 57.0, 49.0, 43.0, 34.0,
    28.0, 25.0, 22.0, 18.0, 14.0, 12.0, 11.0, 8.5, 7.1, 6.1, 5.4, 4.3, 3.6, 3.1]
PLFOS_SCALE = [0.0, 3.61, 7.22, 14.44, 28.88, 57.75, 115.5, 231.0]


def calc_eg_steps(t):
    allsteps = 1024 * (1 << EG_STEP_BITS) - 1
    if t < 0:
        return 0
    if t == 0:
        return allsteps
    scnt = 44.1 * t
    return int(round(allsteps / scnt))


def calc_attack_eg_steps(t):
    if t < 0:
        return 0
    if t == 0:
        return 1 << AEG_ATTACK_SHIFT
    scnt = 44.1 * t
    factor = (1.0 / (1.0 - 1.0 / math.pow(0x280, 1.0 / scnt))) * (1 << AEG_ATTACK_SHIFT)
    return int(round(factor))


def fmt(name, ctype, values, per_line=8):
    out = ['static constexpr %s %s[%d] = {' % (ctype, name, len(values))]
    for i in range(0, len(values), per_line):
        out.append('    ' + ', '.join(str(v) for v in values[i:i + per_line]) + ',')
    out.append('};')
    return '\n'.join(out)


volume_lut = [0] + [int((1 << 15) / math.pow(2.0, (15 - i) / 2.0)) for i in range(1, 16)]
tl_lut = [int((1 << 15) / math.pow(2.0, i / 16.0)) for i in range(256)] + [0] * 768
aeg_att = [calc_attack_eg_steps(t) for t in AEG_ATTACK_TIME]
aeg_dsr = [calc_eg_steps(t) for t in AEG_DSR_TIME]
plfo = []
for s in range(8):
    limit = PLFOS_SCALE[s]
    plfo.append([int(1024.0 * math.pow(2.0, limit * i / 128.0 / 1200.0)) for i in range(-128, 128)])

lines = ['// Generated by tools/aica/gen_tables.py. Do not edit.',
         '// Lookup tables of the AICA mixer (Flycast sgc_if.cpp staticinitialise), fixed so every host',
         '// mixes bit-identically (ADR 16).',
         fmt('kVolumeLut', 'std::int32_t', volume_lut),
         fmt('kTlLut', 'std::int32_t', tl_lut, 16),
         fmt('kAegAttackSps', 'std::uint32_t', aeg_att),
         fmt('kAegDsrSps', 'std::uint32_t', aeg_dsr),
         'static constexpr int kPlfoScales[8][256] = {']
for s in range(8):
    lines.append('    {')
    for i in range(0, 256, 16):
        lines.append('        ' + ', '.join(str(v) for v in plfo[s][i:i + 16]) + ',')
    lines.append('    },')
lines.append('};')
pathlib.Path('runtime/src/aica/mixer_tables.inc').write_text('\n'.join(lines) + '\n')
print('wrote runtime/src/aica/mixer_tables.inc')
